export type Continent =
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Africa'
  | 'Oceania'
  | 'Antarctica';

export const CONTINENTS: readonly Continent[] = [
  'Asia',
  'Europe',
  'North America',
  'South America',
  'Africa',
  'Oceania',
  'Antarctica',
];

export type Category =
  | 'people'
  | 'nature'
  | 'city'
  | 'architecture'
  | 'animal'
  | 'other';

export const CATEGORIES: readonly Category[] = [
  'people',
  'nature',
  'city',
  'architecture',
  'animal',
  'other',
];

export type MediumType = 'digital' | 'film' | 'phone';

export const MEDIUM_TYPES: readonly MediumType[] = ['digital', 'film', 'phone'];

export interface Photo {
  id: string; // slug, unique, stable — e.g. "lisboa-2024-03"
  filename: string; // file in /public/photos/ — e.g. "lisboa-2024-03.webp"
  width: number; // intrinsic px, required for layout without CLS
  height: number; // intrinsic px
  blurDataURL?: string; // base64 LQIP, generated by the add-photo script
  featured: boolean; // pins to top of grid
  title?: string; // optional, shown in lightbox only
  location: {
    city: string;
    country: string;
    continent: Continent;
  };
  year: number;
  medium: {
    type: MediumType;
    camera: string; // camera key, see data/cameras.ts
    filmStock?: string; // required iff type === 'film'
  };
  category: Category;
}
